### ISSUE TITLE
Error message when searching in second window

### ISSUE THREAD

**Issue by MedicalAnimal** [Arthur-Milchior/anki-Multiple-Windows#12]
![image](https://user-images.githubusercontent.com/122030506/211147202-d8621c01-eea2-45fc-9030-298714a5ead2.png)

The way I work is, having 3 windows open in addition to the main window: 2 for browsing, 1 for adding cards

It works well for some period of time and then suddenly I get this error message:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-06 18:13:40

Caught exception:
RuntimeError: wrapped C/C++ object of type QtClassProxy has been deleted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Anonymous\AppData\Roaming\Anki2\addons21\2040501954\browser_replacer.py", line 44, in on_text_edited
    self._check_for_replacement(current_text, False)
  File "C:\Users\Anonymous\AppData\Roaming\Anki2\addons21\2040501954\browser_replacer.py", line 61, in _check_for_replacement
    search_box = self.get_search_box()
SystemError: _PyEval_EvalFrameDefault returned a result with an error set

Caught exception:
RuntimeError: wrapped C/C++ object of type QtClassProxy has been deleted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Anonymous\AppData\Roaming\Anki2\addons21\2040501954\browser_replacer.py", line 44, in on_text_edited
    self._check_for_replacement(current_text, False)
  File "C:\Users\Anonymous\AppData\Roaming\Anki2\addons21\2040501954\browser_replacer.py", line 61, in _check_for_replacement
    search_box = self.get_search_box()
SystemError: _PyEval_EvalFrameDefault returned a result with an error set

**Comment by marcuselias** [comment]
Same Problem here!

**Comment by Arthur-Milchior** [comment]
I'm sorry, but why do you expect this is related to my addon?
If you look at the text you pasted, it shows add-on [2040501954](https://ankiweb.net/shared/info/2040501954)

What other add-on do you have ? Those other add-on state that it's not compatible with [Multi-Column Note Editor](https://ankiweb.net/shared/info/3491767031) so maybe you have found the already existing issue
