### ISSUE TITLE
Major error, undid any thing I unsuspended or studied recently 

### ISSUE THREAD

**Issue by DoctorToBeIn23** [Arthur-Milchior/anki-Multiple-Windows#4]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-28 12:06:40
Add-ons possibly involved: ⁨Opening the same window multiple time, Web Browser - Search terms Import texts and images automatically⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/864545277/browser.py", line 104, in kloseBrowser
    return fn(evt)
  File "aqt/main.py", line 942, in closeEvent
  File "aqt/main.py", line 408, in unloadProfileAndExit
  File "aqt/main.py", line 383, in unloadProfile
  File "aqt/main.py", line 476, in unloadCollection
  File "aqt/main.py", line 747, in closeAllWindows
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/354407385/__init__.py", line 124, in closeAll
    return super().closeAll(onsuccess)
  File "aqt/__init__.py", line 121, in closeAll
RuntimeError: wrapped C/C++ object of type Browser has been deleted

**Comment by Arthur-Milchior** [comment]
Can you please give more detail. What occured when you did that ? I assume you were either syncing or closing the app.

What is "recently" ? This day, this week ? Those past 5 minutes ?

This error occur sometime, it means that a browser window was tried to be closed twice. There is little I can do about it given the way anki manage windows.
But it should not change anything with database and collection, so I really highly doubt this add-on deal with suspending/study.

Please note that the error message also contains `864545277`, which is add-on https://ankiweb.net/shared/info/864545277 ; however I also doubt this is related to your problem

**Comment by DoctorToBeIn23** [comment]
It has happened twice this week when I was studying and unsupendeding cards in a filtered deck and when I tried to close the app I got this error. When I went back in the cards were suspended and not reviewed.

**Comment by Arthur-Milchior** [comment]
Did you try turning this add-on ? Does it makes the problem disappear ? i'd be quite surprised that the problem is related to this add-on. I don't know how many add-ons you have

**Comment by DoctorToBeIn23** [comment]
I have too many to count and can’t reproduce it intentionally I will let you know in the future if I figure out the problem

**Comment by Arthur-Milchior** [comment]
I know this problem very well, having too many add-ons.
